apiVersion: apps/v1
kind: Deployment
metadata:
  name: front50
  namespace: spinnaker
spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: spinnaker-keel-demo-front50
      securityContext:
        fsGroup: 100
      