apiVersion: apps/v1
kind: Deployment
metadata:
  name: clouddriver
  namespace: spinnaker
spec:
  template:
    spec:
      volumes:
      - name: kubeconfig-volume
        secret:
          secretName: kubeconfig-deploy
      containers:
      - name: clouddriver
        volumeMounts:
        - mountPath: /var/kubeconfig
          name: kubeconfig-volume
        resources:
            limits: 
              cpu: "500m"
            requests:
              cpu: "400m"
      serviceAccountName: clouddriver-service-account
      securityContext:
        fsGroup: 100