apiVersion: apps/v1
kind: Deployment
metadata:
  name: clouddriver
  namespace: spinnaker
spec:
  template:
    spec:
      serviceAccountName: spinnaker-keel-demo-clouddriver
      volumes:
      - name: kubeconfig-volume
        secret:
          secretName: kubeconfig-deploy
      containers:
      - name: clouddriver
        volumeMounts:
        - mountPath: /var/kubeconfig
          name: kubeconfig-volume
          