apiVersion: v1
kind: ServiceAccount
metadata:
  name: deploy-service-account
  namespace: keel
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deploy-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: deploy-service-account
  namespace: keel